package Visao;
import aulaqualidade.AulaQualidade;

public class MenuAluno extends javax.swing.JPanel {

    public MenuAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarAluno = new javax.swing.JButton();
        jButtonCadastrarEstagiario = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(735, 532));

        jButtonCadastrarAluno.setText("Cadastrar Aluno");
        jButtonCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarAlunoActionPerformed(evt);
            }
        });

        jButtonCadastrarEstagiario.setText("Cadastrar Estagiário");
        jButtonCadastrarEstagiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarEstagiarioActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabelTitulo.setText("Cadastros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastrarEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(39, 39, 39)
                .addComponent(jButtonCadastrarAluno)
                .addGap(41, 41, 41)
                .addComponent(jButtonCadastrarEstagiario)
                .addContainerGap(399, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarAlunoActionPerformed
        // TODO add your handling code here:
        AulaQualidade.janela.setContentPane(AulaQualidade.CadastroAluno);
        AulaQualidade.janela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarAlunoActionPerformed

    private void jButtonCadastrarEstagiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarEstagiarioActionPerformed
        // TODO add your handling code here:
        AulaQualidade.janela.setContentPane(AulaQualidade.CadastroEstagiario);
        AulaQualidade.janela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarEstagiarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarAluno;
    private javax.swing.JButton jButtonCadastrarEstagiario;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
